Rewrote eps.py to implement logging messages and error handling
TJREVERB/pfs pull request #29
Opened 2019-09-19 22:20 UTC by JayChen35

#18

2019-09-19 22:25 UTC, ayusher submitted a review, later dismissed

2019-09-21 16:29 UTC, abagali1 requested changes
LOVING the documentation. I made a few changes above, but otherwise great work. I am going to hold off merging these changes until we can run through a full unit test with the eps board. (unless there is a pressing reason to merge these changes now)

2019-09-21 16:29 UTC, abagali1 commented on config/config_OLD_default.yml
> +core:
We dont need to store old copies of this. Everything is already saved in `git`s history

2019-09-21 16:29 UTC, abagali1 commented on config/config_default.yml
> +# Simulate = whether or not core is running while running fake data
`simulate` is deprecated. This line is unnecessary

2019-09-21 16:29 UTC, abagali1 commented on config/config_default.yml
> -    dump_interval: 10
keep `dump_interval` under the `core` key b/c it is the interval on which `core` tells `telemetry` its time to send info down in a dump

2019-09-21 16:29 UTC, abagali1 commented on submodules/eps/__init__.py
>  address = 0x57
Do not initialize variables outside a method scope b/c these variables will be reinitialized whenever the module is imported. (i.e. variables will be reinitialized if two different files import this file). Instead, initialize these variables (and any other global variables) in the `start()` method so they are only initialized once.
```
def start():
    global epsdict
    epsdict = {...}
```

2019-09-21 16:29 UTC, abagali1 commented on submodules/eps/__init__.py
> +with open('config/config_default.yml') as stream:
During the startup sequence, `core` reads from the `config_defaul.yml` file and loads it into memory by storing it inside a global variable in `core` called `config`. Reloading the `config_default.yml` file in each module would be a waste of memory and also removes the functionality of having a `config_custom.yml` file during development. Instead, use `from core import config` and reference the `config` variable when you need to read configuration data

2019-09-21 16:29 UTC, abagali1 commented on submodules/eps/__init__.py
>  def start():
Update this method with any global variable initializations listed above.

2019-09-21 16:31 UTC, ayusher submitted a review, later dismissed

2019-10-15 03:24 UTC, abagali1 submitted a review, later dismissed

2019-10-15 03:29 UTC, abagali1 approved these changes

2019-10-15 03:30 UTC, merged